config/routes.rb
Rails.application.routes.draw do
  get 'landing_pages/show', to: 'landing_pages#show'
  root to: 'users#index'
  get 'users/:id/my_page', to: 'users#my_page', as: :user_my_page
  get 'users/:id/user_info', to: 'users#user_info', as: :user_info

  post '/users/:user_id/menus/confirm', to: 'menus#confirm', as: :confirm_user_menu
  post 'users/:user_id/menus/units', to: 'menus#units'

  # ユーザーが作成したmenu用のルーティング
  get 'users/:user_id/custom_menus', to: 'menus#custom_menus', as: :user_custom_menus

  # 標準menu用のルーティング
  get 'sample_menus', to: 'menus#sample_menus', as: :sample_menus

  # CartItem#createへのルーティング
  resources :cart_items
  resources :shopping_lists
  post 'shopping_lists/check_items', to: 'shopping_lists#check_items'

  # カートアイテムの数量を増やす
  post '/cart_items/:id/increment', to: 'cart_items#increment', as: 'cart_item_increment'
  # カートアイテムの数量を減らす
  post '/cart_items/:id/decrement', to: 'cart_items#decrement', as: 'cart_item_decrement'
  post '/shopping_lists/:id/toggle_check', to: 'shopping_lists#toggle_check', as: 'shopping_list_toggle_check'

  resources :cooking_flows do
    member do
      patch :complete
    end
  end

  devise_for :users
  devise_scope :user do
    get 'users/confirmation/custom_confirm', to: 'custom_confirmations#custom_confirm', as: :custom_user_confirmation
    get 'users/confirmation/resend', to: 'custom_confirmations#show_resend_confirmation_form', as: :show_resend_confirmation_form

    get 'guest_sign_in', to: 'custom_sessions#guest_sign_in'

    get 'users/registration', to: 'custom_registrations#new', as: :new_user_custom_registration
    post 'users/registration', to: 'custom_registrations#create', as: :user_custom_registration
    get 'users/session', to: 'custom_sessions#new', as: :new_user_custom_session
    post 'users/session', to: 'custom_sessions#create', as: :user_custom_session
    get 'users/sessions', to: 'custom_sessions#destroy', as: :destroy_user_custom_session

    # パスワードを忘れた場合の処理に関するルーチング
    get 'password/request_reset', to: 'custom_passwords#request_reset', as: :request_reset_password
    post 'password/send_reset_instructions', to: 'custom_passwords#send_reset_instructions', as: :send_reset_instructions
    get 'password/verify_reset_token', to: 'custom_passwords#verify_reset_token', as: :verify_reset_token
    get 'password/edit', to: 'custom_passwords#edit_password', as: :edit_password
    patch 'password/update', to: 'custom_passwords#update_password', as: :update_password

    # ユーザー名更新用のルーティング
    get 'registrations/edit_user_name', to: 'custom_registrations#edit_user_name', as: :edit_user_name_custom_registration
    patch 'registrations/user_name_update', to: 'custom_registrations#user_name_update', as: :user_name_update_custom_registration
    # メールアドレス更新用のルーティング
    get 'registrations/edit_email', to: 'custom_registrations#edit_email', as: :edit_email_custom_registration
    patch 'registrations/email_update', to: 'custom_registrations#email_update', as: :email_update_custom_registration
    # パスワード更新用のルーティング
    get 'registrations/edit_password', to: 'custom_registrations#edit_password', as: :edit_password_user_custom_registration
    patch 'registrations/update_password_info', to: 'custom_registrations#password_info_update', as: :password_info_update_custom_registration

    resources :users do
      resources :menus do
        post 'new', on: :collection, to: 'menus#new', as: :new_user_menu
        post 'edit', on: :collection, to: 'menus#edit', as: :edit_confirm
        post :change_serving_size
        resources :ingredients
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :user_menu, dependent: :destroy
  has_many :menus, through: :user_menu
  has_one :cart, dependent: :destroy
  has_many :shopping_lists, dependent: :destroy

  validates :name, presence: { message: "ユーザー名は必須です。" },
  length: { minimum: 2, too_short: "ユーザー名は最低%{count}文字必要です。", maximum: 15, too_long: "ユーザー名は最大%{count}文字までです。" }, if: :user_info_change_or_new_record?

  # メールアドレスのバリデーション
  validates :email, presence: { message: "メールアドレスは必須です。" },
    uniqueness: { case_sensitive: false, message: "このメールアドレスは既に使用されています。" },
    length: { maximum: 254, too_long: "メールアドレスは最大%{count}文字までです。" },
    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/, message: "メールアドレスの形式が不正です。" }, if: :email_change_or_new_record?

  # パスワードのバリデーションを新規作成と更新の両方で適用
  # パスワードが変更された場合、または新規作成の場合に検証する
  validates :password, length: { minimum: 8, maximum: 128, too_short: "パスワードは最低%{count}文字必要です。", too_long: "パスワードは最大%{count}文字までです。" }, if: :password_change_or_new_record?
  validates :password, confirmation: { message: "新しいパスワードと確認用パスワードが一致しません。" },
    format: { with: /\A(?=.*[a-zA-Z])(?=.*\d)[A-Za-z\d\W_]*\z/, message: "パスワードは8~128で、英字と数字を含んでください（記号は任意）。" }, if: :password_change_or_new_record?

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :confirmable
  attr_accessor :current_password, :user_info_change, :password_change, :new_record, :email_change

  private

  # ユーザー名更新or新規登録の場合にバリデーションを行うための設定
  def user_info_change_or_new_record?
    user_info_change || new_record
  end

  # メールアドレス更新or新規登録の場合にバリデーションを行うための設定
  def email_change_or_new_record?
    email_change || new_record
  end

  # パスワード更新or新規登録の場合にバリデーションを行うための設定
  def password_change_or_new_record?
    password_change || new_record
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include Devise::Controllers::Helpers
  before_action :authenticate_user!

  # ホーム画面のアクション
  def index
    @cart_items = cart_items.includes(:menu).order(:added_at) if current_user_cart
  end

  # マイページ画面のアクション
  def my_page
  end

  # ユーザー情報画面のアクション
  def user_info
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_quantity.html.erb
<%= cart_item.item_count %>

app/views/users/index.html.erb
<%= render 'shared/menu' %>

<div class="menu-index-container" id="menu-index">

  <div class="menu-heading">
    <h3>選択されたレシピ</h3>
  </div>

  <% if @cart_items.present? %>
    <div class="menus_list">
      <% @cart_items.each do |cart_item| %>
        <div class="menu-item">
          <%= button_to '✖️', cart_item_path(cart_item), method: :delete, class: "delete-button", params: { menu_id: cart_item.menu_id } %>

          <%= image_tag(rails_blob_path(cart_item.menu.image.variant(resize_to_fill: [220, 140])), class: "rounded-image") %>
          <div class="menu-item-title"><%= truncate(cart_item.menu.menu_name, length: 10, omission: '..') %></div>

          <div class="menu-item-count">
            <%= button_to '◀︎', cart_item_decrement_path(cart_item), method: :post, class: "decrement-button", params: { menu_id: cart_item.menu_id, item_count: cart_item.item_count } %>

            <div id="menu-item-quantity-<%= cart_item.menu_id %>" class="menu-item-quantity">
              <%= render 'users/quantity', cart_item: cart_item %>
            </div>

            <%= button_to '▶︎', cart_item_increment_path(cart_item), method: :post, class: "increment-button" %>
          </div>
        </div>
      <% end %>
    </div>
  <% else %>
    <p class="empty-cart-message">レシピが選択されていません。</p>
  <% end %>

  <div class="button-set-container">
    <%= button_to "レシピを作る・選ぶ", sample_menus_path, class: "button-style bg-standard-menu", method: :get %>
    <%= button_to "買い物リスト", shopping_lists_path, class: "button-style bg-shopping-list", method: :post, id: "shopping-list" %>
    <%= button_to "レシピを確認", cooking_flows_path, class: "button-style bg-standard-menu", method: :get %>
  </div>
</div>

app/views/users/my_page.html.erb
<div class="my-page-container">

  <div class="my-page-title">
    <h1>マイページ</h1>
  </div>

  <div class="my-page-input">

    <div class="my-page-button">
      <%= button_to "ユーザー情報", user_info_path, class: "my-page-button", method: :get %>
    </div>

    <div class="my-page-button">
      <%= button_to "ログアウト", destroy_user_custom_session_path, class: "log-out-button", method: :get, form: { data: { turbo_confirm: "ログアウトしてもよろしいですか？" }} %>
    </div>

    <div class="my-page-back-button">
      <%= button_to "戻る", root_path, class: "back-button", method: :get %>
    </div>
  </div>
</div>

app/views/users/user_info.html.erb
<div class="user-info-container">

  <div class="user-info-title">
    <h1>ユーザー情報</h1>
  </div>

  <div class="my-page-input">

    <div class="user-details-container">
      <p class="label">ユーザー名:</p>
      <div class="detail-and-edit">
        <p class="detail"><%= @user.name %></p>
        <%= link_to "変更", edit_user_name_custom_registration_path, class: "edit-link" %>
      </div>
    </div>

    <div class="user-details-container">
      <p class="label">メールアドレス:</p>
      <div class="detail-and-edit">
        <p class="detail"><%= @user.email %></p>
        <%= link_to "変更", edit_email_custom_registration_path, class: "edit-link" %>
      </div>
    </div>

    <div class="user-details-container">
      <p class="label">パスワード:</p>
      <div class="detail-and-edit">
        <p class="detail">••••••••</p>
        <%= link_to "変更", edit_password_user_custom_registration_path, class: "edit-link" %>
      </div>
    </div>
  </div>

  <div class="my-page-back-button">
    <%= button_to "戻る", root_path, class: "back-button", method: :get %>
  </div>
</div>