config/routes.rb
Rails.application.routes.draw do
  get 'landing_pages/show', to: 'landing_pages#show'
  root to: 'users#index'
  get 'users/:id/my_page', to: 'users#my_page', as: :user_my_page
  get 'users/:id/user_info', to: 'users#user_info', as: :user_info

  post '/users/:user_id/menus/confirm', to: 'menus#confirm', as: :confirm_user_menu
  post 'users/:user_id/menus/units', to: 'menus#units'

  # ユーザーが作成したmenu用のルーティング
  get 'users/:user_id/custom_menus', to: 'menus#custom_menus', as: :user_custom_menus

  # 標準menu用のルーティング
  get 'sample_menus', to: 'menus#sample_menus', as: :sample_menus

  # CartItem#createへのルーティング
  resources :cart_items
  resources :shopping_lists
  post 'shopping_lists/check_items', to: 'shopping_lists#check_items'

  # カートアイテムの数量を増やす
  post '/cart_items/:id/increment', to: 'cart_items#increment', as: 'cart_item_increment'
  # カートアイテムの数量を減らす
  post '/cart_items/:id/decrement', to: 'cart_items#decrement', as: 'cart_item_decrement'
  post '/shopping_lists/:id/toggle_check', to: 'shopping_lists#toggle_check', as: 'shopping_list_toggle_check'

  resources :cooking_flows do
    member do
      patch :complete
    end
  end

  devise_for :users
  devise_scope :user do
    get 'users/confirmation/custom_confirm', to: 'custom_confirmations#custom_confirm', as: :custom_user_confirmation
    get 'users/confirmation/resend', to: 'custom_confirmations#show_resend_confirmation_form', as: :show_resend_confirmation_form

    get 'guest_sign_in', to: 'custom_sessions#guest_sign_in'

    get 'users/registration', to: 'custom_registrations#new', as: :new_user_custom_registration
    post 'users/registration', to: 'custom_registrations#create', as: :user_custom_registration
    get 'users/session', to: 'custom_sessions#new', as: :new_user_custom_session
    post 'users/session', to: 'custom_sessions#create', as: :user_custom_session
    get 'users/sessions', to: 'custom_sessions#destroy', as: :destroy_user_custom_session

    # パスワードを忘れた場合の処理に関するルーチング
    get 'password/request_reset', to: 'custom_passwords#request_reset', as: :request_reset_password
    post 'password/send_reset_instructions', to: 'custom_passwords#send_reset_instructions', as: :send_reset_instructions
    get 'password/verify_reset_token', to: 'custom_passwords#verify_reset_token', as: :verify_reset_token
    get 'password/edit', to: 'custom_passwords#edit_password', as: :edit_password
    patch 'password/update', to: 'custom_passwords#update_password', as: :update_password

    # ユーザー名更新用のルーティング
    get 'registrations/edit_user_name', to: 'custom_registrations#edit_user_name', as: :edit_user_name_custom_registration
    patch 'registrations/user_name_update', to: 'custom_registrations#user_name_update', as: :user_name_update_custom_registration
    # メールアドレス更新用のルーティング
    get 'registrations/edit_email', to: 'custom_registrations#edit_email', as: :edit_email_custom_registration
    patch 'registrations/email_update', to: 'custom_registrations#email_update', as: :email_update_custom_registration
    # パスワード更新用のルーティング
    get 'registrations/edit_password', to: 'custom_registrations#edit_password', as: :edit_password_user_custom_registration
    patch 'registrations/update_password_info', to: 'custom_registrations#password_info_update', as: :password_info_update_custom_registration

    resources :users do
      resources :menus do
        post 'new', on: :collection, to: 'menus#new', as: :new_user_menu
        post 'edit', on: :collection, to: 'menus#edit', as: :edit_confirm
        post :change_serving_size
        resources :ingredients
      end
    end
  end
end

app/controllers/custom_registrations_controller.rb
class CustomRegistrationsController < ApplicationController
  include FlashAndRedirect
  include SetValidationErrorHelper
  skip_before_action :authenticate_user!, only: [:new, :create]

  def new
    @user = User.new
  end


  def create
    #user情報を格納する
    user = User.new(registration_params)

    if user_info_missing? && password_info_missing?
      set_flash_and_redirect(:error, "未入力があります。", new_user_custom_registration_path)
      return
    end

    if user.save
      redirect_to show_resend_confirmation_form_path(user_id: user.id)
    else
      set_flash_and_redirect(:error, set_validation_error(user), new_user_custom_registration_path)
    end
  end


  # ユーザー名の変更画面
  def edit_user_name
  end


  # ユーザー名の変更アクション
  def user_name_update
    if params[:user][:name].blank?
      set_flash_and_redirect(:error, "未入力があります。", edit_user_name_custom_registration_path)
      return
    end

    if current_user.update(registration_params)
      set_flash_and_redirect(:notice, "ユーザー名を更新しました。", edit_user_name_custom_registration_path)
    else
      set_flash_and_redirect(:error, set_validation_error(current_user), edit_user_name_custom_registration_path)
    end
  end


  # メールアドレスの変更画面
  def edit_email
  end


  # メールアドレスの変更アクション
  def email_update
    if params[:user][:email].blank?
      set_flash_and_redirect(:error, "未入力があります。", edit_email_custom_registration_path)
      return
    end

    # 入力されたメールアドレスが現在のメールアドレスと同じかどうかをチェック
    if params[:user][:email] == current_user.email
      set_flash_and_redirect(:error, "登録済みのアドレスです。", edit_email_custom_registration_path)
      return
    end

    # 新しいメールアドレスに確認メールを送信
    if current_user.update(registration_params)
      set_flash_and_redirect(:notice, "メールアドレス更新の確認メールを送信しました。", edit_email_custom_registration_path)
    else
      set_flash_and_redirect(:error, set_validation_error(current_user), edit_email_custom_registration_path)
    end
  end


  # パスワードの変更画面
  def edit_password
  end


  # パスワードの変更アクション
  def password_info_update
    if password_info_missing?
      set_flash_and_redirect(:error, "未入力があります。", edit_password_user_custom_registration_path)
      return
    end

    if !current_user.valid_password?(params[:user][:current_password])
      set_flash_and_redirect(:error, "現在のパスワードが正しくありません。", edit_password_user_custom_registration_path)
      return
    end

    if current_user.update(registration_params)
      set_flash_and_redirect(:notice, "パスワードを更新しました。再度ログインをお願いします。", root_path)
    else
      set_flash_and_redirect(:error, set_validation_error(current_user), edit_password_user_custom_registration_path)
      return
    end
  end

  private

  # ユーザー情報関連のパラメータが提供されているか確認
  # フィールドの未入力チェックはコントローラーレベルで行う。
  # モデルのバリデーションでは、フィールドが空の場合のチェックができないため、
  # 未入力の状態で適切なエラーメッセージを提供するためにはコントローラーでのチェックが必要。
  def user_info_missing?
    params[:user][:name].blank? || params[:user][:email].blank?
  end

  #「if user_info_missing?」での説明と同様
  def password_info_missing?
    params[:user][:current_password].blank? ||
    params[:user][:password].blank? ||
    params[:user][:password_confirmation].blank?
  end

  def registration_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password, :user_info_change, :email_change, :password_change)
  end
end

app/helpers/custom_registrations_helper.rb
module CustomRegistrationsHelper
end

app/views/custom_registrations/edit.html.erb
<div class="edit-registration-container">

  <div class="registration-title">
    <h1>ユーザー情報更新</h1>
  </div>

  <div class="registration-instructions">
    <p>登録内容は管理者および本人以外には公開されません。</p>
  </div>

  <div class="registration-input">
    <%= form_with model: current_user, url: update_user_custom_registration_path, local: true, method: :patch do |f| %>
      <div class="registration-field">
        <%= f.text_field :name, autofocus: true, autocomplete: "name", placeholder: "ユーザー名" %>
      </div>

      <div class="registration-field">
        <%= f.email_field :email, autofocus: true, autocomplete: "email", placeholder: "メールアドレス" %>
      </div>

      <div class="registration-link">
        <%= link_to "パスワードを変更する", edit_password_user_custom_registration_path, class: "password-change-link" %>
      </div>

      <div class="registration-actions">
        <%= f.submit "更新" %>
      </div>
    <% end %>
    <div class="registration-back-button">
      <%= button_to "戻る", root_path, class: "back-button", method: :get %>
    </div>
  </div>
</div>

app/views/custom_registrations/edit_email.html.erb
<div class="edit-registration-container" id="email-validation-area">

  <div class="registration-title">
    <h1>メールアドレス変更</h1>
  </div>

  <div class="registration-instructions">
    <p>変更手続きでは、入力されたメールアドレスへ<br>
    確認メールをお送りいたします。</p>

    <p>セキュリティ保護のため、メールに記載された<br>
    リンクは24時間後に無効となります。</p>
  </div>

  <div class="registration-input">
    <%= form_with model: current_user, url: email_update_custom_registration_path, local: true, method: :patch do |f| %>
      <%= f.hidden_field :email_change, value: true %>

      <div class="registration-field">
        <div class="error-message"></div>
        <%= f.email_field :email, autofocus: false, autocomplete: "email", placeholder: "メールアドレス" %>
      </div>

      <div class="registration-actions">
        <%= f.submit "確認メールを送信", id: "update-user-submit" %>
      </div>

    <% end %>
    <div class="registration-back-button">
    <%= button_to "戻る", user_info_path(current_user), class: "back-button", method: :get %>
    </div>
  </div>
</div>

app/views/custom_registrations/edit_password.html.erb
<div class="edit-registration-container" id="password-validation-area">

  <div class="registration-title">
    <h1>パスワード変更</h1>
  </div>

  <div class="registration-instructions">
    <p>更新後、新しいパスワードで再ログインが必要です。<br>
    ※パスワードの変更は8~128文字、英数字を含んでください。</p>
  </div>

  <div class="registration-input">
    <%= form_with model: current_user, url: password_info_update_custom_registration_path, local: true, method: :patch do |f| %>
      <%= f.hidden_field :password_change, value: true %>

      <div class="registration-field">
        <div class="error-message"></div>
        <%= f.text_field :current_password, autofocus: false, name: 'user[current_password]', autocomplete: "off", placeholder: "現在のパスワードを入力" %>
      </div>

      <div class="registration-field">
        <div class="error-message"></div>
        <%= f.password_field :password, autofocus: false, name: 'user[password]', autocomplete: "off", placeholder: "新しいパスワードを入力" %>
      </div>

      <div class="registration-field">
        <div class="error-message"></div>
        <%= f.password_field :password_confirmation, autofocus: false, name: 'user[password_confirmation]', autocomplete: "off", placeholder: "もう一度新しいパスワードを入力" %>
      </div>

      <div class="registration-link">
        <%= link_to 'パスワードを忘れた方はこちら', request_reset_password_path %>
      </div>

      <div class="registration-actions">
        <%= f.submit "変更", id: "update-password-submit" %>
      </div>
    <% end %>
    <div class="registration-back-button">
      <%= button_to "戻る", user_info_path(current_user), class: "back-button", method: :get %>
    </div>
  </div>
</div>

app/views/custom_registrations/edit_user.html.erb
<div class="edit-registration-container">

  <div class="registration-title">
    <h1>ユーザー情報更新</h1>
  </div>

  <div class="registration-instructions">
    <p>登録内容は管理者および本人以外には公開されません。</p>
  </div>

  <div class="registration-input">
    <%= form_with model: current_user, url: user_info_update_custom_registration_path, local: true, method: :patch do |f| %>
      <div class="registration-field">
        <%= f.text_field :name, autofocus: true, autocomplete: "name", placeholder: "ユーザー名", maxlength: 8 %>
      </div>

      <div class="registration-field">
        <%= f.email_field :email, autofocus: true, autocomplete: "email", placeholder: "メールアドレス", maxlength: 254 %>
      </div>

      <div class="registration-link">
        <%= link_to "パスワードを変更する", edit_password_user_custom_registration_path, class: "password-change-link" %>
      </div>

      <div class="registration-actions">
        <%= f.submit "更新", id: "update-user-submit" %>
      </div>

    <% end %>
    <div class="registration-back-button">
      <%= button_to "戻る", root_path, class: "back-button", method: :get %>
    </div>
  </div>
</div>

<%= javascript_include_tag 'user_validation' %>

app/views/custom_registrations/edit_user_name.html.erb
<div class="edit-registration-container" id="user-name-validation-area">

  <div class="registration-title">
    <h1>ユーザー名変更</h1>
  </div>

  <div class="registration-instructions">
    <p>ユーザー名は2〜15文字で設定をしてください。</p>
  </div>

  <div class="registration-input">
    <%= form_with model: current_user, url: user_name_update_custom_registration_path, local: true, method: :patch do |f| %>
      <%= f.hidden_field :user_info_change, value: true %>

      <div class="registration-field">
        <div class="error-message"></div>
        <%= f.text_field :name, autofocus: false, name: 'user[name]', autocomplete: "name", placeholder: "ユーザー名" %>
      </div>

      <div class="registration-actions">
        <%= f.submit "変更" %>
      </div>

    <% end %>
    <div class="registration-back-button">
    <%= button_to "戻る", user_info_path(current_user), class: "back-button", method: :get %>
    </div>
  </div>
</div>

app/views/custom_registrations/new.html.erb
<div class="new-registration-container" id="new-account-validation">

  <div class="registration-title">
    <h1>ユーザー新規登録</h1>
  </div>

  <div class="registration-instructions">
    <p>※未入力があると登録ができません。</p>
  </div>

  <div class="registration-input">
    <%= form_with url: user_custom_registration_path, local: true do |f| %>
      <%= f.hidden_field :new_record, value: true %>

      <div class="registration-field">
        <div class="error-message"></div>
        <%= f.text_field :name, autofocus: false, name: 'user[name]', autocomplete: "name", placeholder: "ユーザー名:2〜15文字" %>
      </div>

      <div class="registration-field">
        <div class="error-message"></div>
        <%= f.email_field :email, autofocus: false, name: 'user[email]', autocomplete: "email", placeholder: "メールアドレス" %>
      </div>

      <div class="registration-field">
        <div class="error-message"></div>
        <%= f.password_field :password, autofocus: false, name: 'user[password]', autocomplete: "password", placeholder: "パスワード:8~128文字の英数字" %>
      </div>

      <div class="registration-field">
        <div class="error-message"></div>
        <%= f.password_field :password_confirmation, autofocus: false, name: 'user[password_confirmation]', autocomplete: "password_confirmation", placeholder: "確認用パスワード" %>
      </div>

      <div class="registration-actions">
        <%= f.submit "登録" %>
      </div>

      <div class="registration-link">
        <%= link_to 'すでに登録された方はこちら', new_user_custom_session_path %>
      </div>
    <% end %>
  </div>
</div>