config/routes.rb
Rails.application.routes.draw do
  get 'landing_pages/show', to: 'landing_pages#show'
  root to: 'users#index'
  get 'users/:id/my_page', to: 'users#my_page', as: :user_my_page
  get 'users/:id/user_info', to: 'users#user_info', as: :user_info

  post '/users/:user_id/menus/confirm', to: 'menus#confirm', as: :confirm_user_menu
  post 'users/:user_id/menus/units', to: 'menus#units'

  # ユーザーが作成したmenu用のルーティング
  get 'users/:user_id/custom_menus', to: 'menus#custom_menus', as: :user_custom_menus

  # 標準menu用のルーティング
  get 'sample_menus', to: 'menus#sample_menus', as: :sample_menus

  # CartItem#createへのルーティング
  resources :cart_items
  resources :shopping_lists
  post 'shopping_lists/check_items', to: 'shopping_lists#check_items'

  # カートアイテムの数量を増やす
  post '/cart_items/:id/increment', to: 'cart_items#increment', as: 'cart_item_increment'
  # カートアイテムの数量を減らす
  post '/cart_items/:id/decrement', to: 'cart_items#decrement', as: 'cart_item_decrement'
  post '/shopping_lists/:id/toggle_check', to: 'shopping_lists#toggle_check', as: 'shopping_list_toggle_check'

  resources :cooking_flows do
    member do
      patch :complete
    end
  end

  devise_for :users
  devise_scope :user do
    get 'users/confirmation/custom_confirm', to: 'custom_confirmations#custom_confirm', as: :custom_user_confirmation
    get 'users/confirmation/resend', to: 'custom_confirmations#show_resend_confirmation_form', as: :show_resend_confirmation_form

    get 'guest_sign_in', to: 'custom_sessions#guest_sign_in'

    get 'users/registration', to: 'custom_registrations#new', as: :new_user_custom_registration
    post 'users/registration', to: 'custom_registrations#create', as: :user_custom_registration
    get 'users/session', to: 'custom_sessions#new', as: :new_user_custom_session
    post 'users/session', to: 'custom_sessions#create', as: :user_custom_session
    get 'users/sessions', to: 'custom_sessions#destroy', as: :destroy_user_custom_session

    # パスワードを忘れた場合の処理に関するルーチング
    get 'password/request_reset', to: 'custom_passwords#request_reset', as: :request_reset_password
    post 'password/send_reset_instructions', to: 'custom_passwords#send_reset_instructions', as: :send_reset_instructions
    get 'password/verify_reset_token', to: 'custom_passwords#verify_reset_token', as: :verify_reset_token
    get 'password/edit', to: 'custom_passwords#edit_password', as: :edit_password
    patch 'password/update', to: 'custom_passwords#update_password', as: :update_password

    # ユーザー名更新用のルーティング
    get 'registrations/edit_user_name', to: 'custom_registrations#edit_user_name', as: :edit_user_name_custom_registration
    patch 'registrations/user_name_update', to: 'custom_registrations#user_name_update', as: :user_name_update_custom_registration
    # メールアドレス更新用のルーティング
    get 'registrations/edit_email', to: 'custom_registrations#edit_email', as: :edit_email_custom_registration
    patch 'registrations/email_update', to: 'custom_registrations#email_update', as: :email_update_custom_registration
    # パスワード更新用のルーティング
    get 'registrations/edit_password', to: 'custom_registrations#edit_password', as: :edit_password_user_custom_registration
    patch 'registrations/update_password_info', to: 'custom_registrations#password_info_update', as: :password_info_update_custom_registration

    resources :users do
      resources :menus do
        post 'new', on: :collection, to: 'menus#new', as: :new_user_menu
        post 'edit', on: :collection, to: 'menus#edit', as: :edit_confirm
        post :change_serving_size
        resources :ingredients
      end
    end
  end
end

app/controllers/custom_passwords_controller.rb
class CustomPasswordsController < ApplicationController
  include SetValidationErrorHelper
  skip_before_action :authenticate_user!

  def request_reset
  end

  def send_reset_instructions
    # メールアドレスが空かどうかを確認
    if params[:user][:email].blank?
      flash[:error] = "未入力があります。"
      redirect_to request_reset_password_path
      return
    end

    # メールアドレスに該当するユーザーを検索
    user = User.find_by(email: params[:user][:email].downcase)

    # ユーザーが存在しない場合の処理
    if user.nil?
      flash[:error] = "該当するユーザーが存在しません。"
      redirect_to request_reset_password_path
      return
    end

    # ユーザーが存在する場合、パスワードリセット用のメールを送信
    user.send_reset_password_instructions
    flash[:notice] = "パスワードリセットに関するご案内メールを送信しました。"
    redirect_to request_reset_password_path
  end

  def verify_reset_token
    # パラメータからトークンを取得
    token = params[:reset_password_token]
    # トークンに対応するユーザーを検索
    user = User.with_reset_password_token(token)

    # ユーザーが存在し、トークンが有効であればパスワード変更フォームへリダイレクト
    if user && user.reset_password_period_valid?
      redirect_to edit_password_path(reset_password_token: token)
    else
      # トークンが無効な場合、エラーメッセージを表示
      flash[:error] = "パスワードリセットトークンが無効か、期限切れです。"
      redirect_to request_reset_password_path
    end
  end

  def edit_password
  end

  def update_password
    if params[:user][:password].blank? || params[:user][:password_confirmation].blank?
      flash[:error] = "未入力があります。"
      redirect_to edit_password_path
      return
    end
    # パラメータからトークンを取得
    token = params[:reset_password_token]

    # トークンに対応するユーザーを検索
    user = User.with_reset_password_token(token)

    # トークンが無効または期限切れである場合の処理
    if user.nil? || !user.reset_password_period_valid?
      flash[:error] = "パスワードの変更期限切れ。再度手続きをお願いします。"
      redirect_to root_path
      return
    end

    # パスワードの更新処理
    # パスワード更新に成功した場合の処理
    if user.update(password_params)
      # パスワードリセットトークンをクリア
      user.update(reset_password_token: nil, reset_password_sent_at: nil)

      flash[:notice] = "パスワードが更新されました。再度ログインをお願いします。"
      redirect_to root_path
    else
      # バリデーションエラーがある場合
      flash[:error] = set_validation_error(user)
      redirect_to edit_password_path(reset_password_token: token)
    end

  end

  private

  def password_params
    params.require(:user).permit(:password, :password_confirmation, :password_change)
  end
end

app/helpers/custom_passwords_helper.rb
module CustomPasswordsHelper
end

app/views/custom_passwords/edit_password.html.erb
<div class="password-update-container" id="password-validation-area">

  <div class="password-update-title">
    <h1>パスワードリセット</h1>
  </div>

  <div class="password-update-instructions">
    <p>更新後、新しいパスワードで再ログインが必要です。<br>
    ※パスワード: パスワードの変更は8~128文字、英数字を含んでください。</p>
  </div>

  <div class="password-update-input">
    <%= form_with url: update_password_path, local: true, method: :patch do |f| %>
      <%= f.hidden_field :password_change, value: true, name: 'user[password_change]' %>
      <%= f.hidden_field :reset_password_token, value: params[:reset_password_token] %>

      <div class="password-update-field">
        <div class="error-message"></div>
        <%= f.password_field :password, autofocus: false, name: 'user[password]', autocomplete: "off", placeholder: "新しいパスワードを入力" %>
      </div>

      <div class="password-update-field">
        <div class="error-message"></div>
        <%= f.password_field :password_confirmation, autofocus: false, name: 'user[password_confirmation]', autocomplete: "off", placeholder: "もう一度新しいパスワードを入力" %>
      </div>

      <div class="password-update-actions">
        <%= f.submit "更新", id: "update-password-submit" %>
      </div>
    <% end %>
  </div>
</div>

app/views/custom_passwords/request_reset.html.erb
<div class="password-reset-request-container" id="email-validation-area">
  <div class="password-reset-request-title">
    <h1>パスワード再設定</h1>
  </div>

  <div class="password-reset-request-instructions">
    <p>入力していただいたメールアドレス宛に、<br>
    再設定のご案内メールが届きます。</p>
  </div>

  <div class="password-reset-request-input">
    <%= form_with url: send_reset_instructions_path, local: true, method: :post do |f| %>
      <div class="password-reset-request-field">
        <div class="error-message"></div>
        <%= f.email_field :email, autofocus: false, name: 'user[email]', autocomplete: "email", placeholder: "メールアドレス" %>
      </div>

      <div class="password-reset-request-actions">
        <%= f.submit "メール送信", id: "send-reset-instructions-submit" %>
      </div>
    <% end %>

    <div class="password-reset-request-back-button">
      <% if session[:user_id] %>
        <%= button_to '戻る', edit_password_user_custom_registration_path, method: :get, class: 'back-button', id: 'back_button' %>
      <% else %>
        <%= button_to '戻る', new_user_custom_session_path, method: :get, class: 'back-button', id: 'back_button' %>
      <% end %>
    </div>
  </div>
</div>